# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeeDataCatalog
                                 A QGIS plugin
 QGIS Plugin to explore Google Earth Engine Data Catalog
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-05-24
        copyright            : (C) 2020 by Sandro Klippel
        email                : sandroklippel@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeeDataCatalog class from file GeeDataCatalog.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgis_gee_data_catalog import GeeDataCatalog
    return GeeDataCatalog(iface)
