# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qgis_gee_data_catalog_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from os.path import isdir

class Ui_GeeDataCatalogDialogBase(object):

    def setupUi(self, GeeDataCatalogDialogBase):
        self._translate = QtCore.QCoreApplication.translate
        GeeDataCatalogDialogBase.setObjectName("GeeDataCatalogDialogBase")
        GeeDataCatalogDialogBase.resize(565, 223)
        GeeDataCatalogDialogBase.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gridLayout = QtWidgets.QGridLayout(GeeDataCatalogDialogBase)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(GeeDataCatalogDialogBase)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.bands = QtWidgets.QComboBox(GeeDataCatalogDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bands.sizePolicy().hasHeightForWidth())
        self.bands.setSizePolicy(sizePolicy)
        self.bands.setObjectName("bands")
        self.gridLayout.addWidget(self.bands, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(GeeDataCatalogDialogBase)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.collection = QtWidgets.QComboBox(GeeDataCatalogDialogBase)
        self.collection.setObjectName("collection")
        self.gridLayout.addWidget(self.collection, 0, 1, 1, 2)
        self.startdate = QtWidgets.QDateEdit(GeeDataCatalogDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startdate.sizePolicy().hasHeightForWidth())
        self.startdate.setSizePolicy(sizePolicy)
        self.startdate.setCalendarPopup(True)
        self.startdate.setObjectName("startdate")
        self.gridLayout.addWidget(self.startdate, 0, 4, 1, 3)
        self.label_4 = QtWidgets.QLabel(GeeDataCatalogDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(GeeDataCatalogDialogBase)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
        self.enddate = QtWidgets.QDateEdit(GeeDataCatalogDialogBase)
        self.enddate.setCalendarPopup(True)
        self.enddate.setObjectName("enddate")
        self.gridLayout.addWidget(self.enddate, 1, 4, 1, 3)
        self.infotext = QtWidgets.QTextEdit(GeeDataCatalogDialogBase)
        self.infotext.setReadOnly(True)
        self.infotext.setObjectName("infotext")
        self.gridLayout.addWidget(self.infotext, 2, 0, 2, 3)
        self.label_5 = QtWidgets.QLabel(GeeDataCatalogDialogBase)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 3, 1, 2)
        self.cloudcover = QtWidgets.QSpinBox(GeeDataCatalogDialogBase)
        self.cloudcover.setProperty("value", 99)
        self.cloudcover.setObjectName("cloudcover")
        self.gridLayout.addWidget(self.cloudcover, 2, 4, 1, 2)
        self.label_6 = QtWidgets.QLabel(GeeDataCatalogDialogBase)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 3, 1, 3)
        self.limit = QtWidgets.QSpinBox(GeeDataCatalogDialogBase)
        self.limit.setMinimum(1)
        self.limit.setMaximum(20)
        self.limit.setProperty("value", 1)
        self.limit.setObjectName("limit")
        self.gridLayout.addWidget(self.limit, 3, 5, 1, 1)
        self.addlayer = QtWidgets.QCheckBox(GeeDataCatalogDialogBase)
        self.addlayer.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.addlayer.setChecked(True)
        self.addlayer.setObjectName("addlayer")
        self.gridLayout.addWidget(self.addlayer, 4, 2, 1, 4)
        self.destination_label = QtWidgets.QLabel(GeeDataCatalogDialogBase)
        self.destination_label.setObjectName("destionation")
        self.gridLayout.addWidget(self.destination_label, 4, 0, 1, 1)
        self.destination_folder = QtWidgets.QLineEdit(GeeDataCatalogDialogBase)
        self.destination_folder.setClearButtonEnabled(True)
        self.destination_folder.setPlaceholderText(self._translate("GeeDataCatalogDialogBase","Temporary Output"))
        self.default_folder = None
        self.gridLayout.addWidget(self.destination_folder, 4, 1, 1, 1)
        self.browse_button = QtWidgets.QPushButton('...',GeeDataCatalogDialogBase)
        self.browse_button.clicked.connect(self.destiation_browse,)
        self.gridLayout.addWidget(self.browse_button, 4, 2, 1, 1)
        self.button_box = QtWidgets.QDialogButtonBox(GeeDataCatalogDialogBase)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.gridLayout.addWidget(self.button_box, 5, 2, 1, 4)

        self.retranslateUi(GeeDataCatalogDialogBase)
        self.button_box.accepted.connect(GeeDataCatalogDialogBase.accept)
        self.button_box.rejected.connect(GeeDataCatalogDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(GeeDataCatalogDialogBase)
        GeeDataCatalogDialogBase.setTabOrder(self.collection, self.bands)
        GeeDataCatalogDialogBase.setTabOrder(self.bands, self.startdate)
        GeeDataCatalogDialogBase.setTabOrder(self.startdate, self.enddate)
        GeeDataCatalogDialogBase.setTabOrder(self.enddate, self.cloudcover)
        GeeDataCatalogDialogBase.setTabOrder(self.cloudcover, self.limit)
        GeeDataCatalogDialogBase.setTabOrder(self.limit, self.addlayer)
        GeeDataCatalogDialogBase.setTabOrder(self.addlayer, self.infotext)

    def retranslateUi(self, GeeDataCatalogDialogBase):

        GeeDataCatalogDialogBase.setWindowTitle(self._translate("GeeDataCatalogDialogBase", "Search Google Earth Engine Data Catalog"))
        self.label.setText(self._translate("GeeDataCatalogDialogBase", "The start date (inclusive):"))
        self.label_3.setText(self._translate("GeeDataCatalogDialogBase", "Dataset"))
        self.startdate.setDisplayFormat(self._translate("GeeDataCatalogDialogBase", "yyyy-MM-dd"))
        self.label_4.setText(self._translate("GeeDataCatalogDialogBase", "Bands"))
        self.label_2.setText(self._translate("GeeDataCatalogDialogBase", "The end date (exclusive):"))
        self.enddate.setDisplayFormat(self._translate("GeeDataCatalogDialogBase", "yyyy-MM-dd"))
        self.label_5.setText(self._translate("GeeDataCatalogDialogBase", "Maximum cloud coverage:"))
        self.cloudcover.setSuffix(self._translate("GeeDataCatalogDialogBase", "%"))
        self.label_6.setText(self._translate("GeeDataCatalogDialogBase", "Maximum number of images:"))
        self.addlayer.setText(self._translate("GeeDataCatalogDialogBase", "Add layer(s) to canvas:"))
        self.destination_label.setText(self._translate("GeeDataCatalogDialogBase", "Output Folder"))

    def destiation_browse(self):
        directory = str(QtWidgets.QFileDialog.getExistingDirectory(self, self._translate("GeeDataCatalogDialogBase","Select Directory"), self.default_folder))

        if directory and isdir(directory):
            self.destination_folder.setText( directory )

